// Code generated by surreal-orm-gen. DO NOT EDIT.

package gogenerate

import (
	"github.com/yaroher/surrealdb.go.orm/pkg/migrator"
	"github.com/yaroher/surrealdb.go.orm/pkg/qb"
)

type AccountSchema struct {
	ID   qb.Field[string]
	Name qb.Field[string]
}

func (a Account) Table() qb.Table {
	return qb.T("account")
}

func (a Account) Schema() AccountSchema {
	return AccountSchema{
		ID:   qb.F[string]("id"),
		Name: qb.F[string]("name"),
	}
}

type UserSchema struct {
	ID        qb.Field[string]
	FirstName qb.Field[string]
	LastName  qb.Field[string]
	Email     qb.Field[string]
}

func (u User) Table() qb.Table {
	return qb.T("users")
}

func (u User) Schema() UserSchema {
	return UserSchema{
		ID:        qb.F[string]("id"),
		FirstName: qb.F[string]("first_name"),
		LastName:  qb.F[string]("last_name"),
		Email:     qb.F[string]("email"),
	}
}

type UserAccountSchema struct {
	Note qb.Field[string]
}

func (u UserAccount) Table() qb.Table {
	return qb.T("user_account")
}

func (u UserAccount) Schema() UserAccountSchema {
	return UserAccountSchema{
		Note: qb.F[string]("note"),
	}
}

func (u UserAccount) EdgeIn() qb.Table {
	return qb.T("user")
}

func (u UserAccount) EdgeOut() qb.Table {
	return qb.T("account")
}

func Resources() migrator.ResourceSet {
	res := migrator.NewResourceSet()
	res.AddTable("account", qb.DefineTableName("account").PermissionsFull())
	res.AddField("account", "id", qb.DefineFieldName("id", "account").Type("record<account>"))
	res.AddField("account", "name", qb.DefineFieldName("name", "account").Type("string"))
	res.AddTable("users", qb.DefineTableName("users").PermissionsFull())
	res.AddField("users", "id", qb.DefineFieldName("id", "users").Type("record<users>"))
	res.AddField("users", "first_name", qb.DefineFieldName("first_name", "users").Type("string"))
	res.AddField("users", "last_name", qb.DefineFieldName("last_name", "users").Type("string"))
	res.AddField("users", "email", qb.DefineFieldName("email", "users").Type("string"))
	res.AddTable("user_account", qb.DefineTableName("user_account"))
	res.AddField("user_account", "note", qb.DefineFieldName("note", "user_account").Type("string"))
	res.AddField("user_account", "in", qb.DefineFieldName("in", "user_account").Type("record<user>"))
	res.AddField("user_account", "out", qb.DefineFieldName("out", "user_account").Type("record<account>"))
	return res
}
