// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protosurrealorm/anotations.proto

package protosurrealorm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	On              string                 `protobuf:"bytes,2,opt,name=on,proto3" json:"on,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Overwrite       bool                   `protobuf:"varint,4,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	IfNotExists     bool                   `protobuf:"varint,5,opt,name=if_not_exists,json=ifNotExists,proto3" json:"if_not_exists,omitempty"`
	Alg             string                 `protobuf:"bytes,6,opt,name=alg,proto3" json:"alg,omitempty"`
	Key             string                 `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	Url             string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	Signup          string                 `protobuf:"bytes,9,opt,name=signup,proto3" json:"signup,omitempty"`
	Signin          string                 `protobuf:"bytes,10,opt,name=signin,proto3" json:"signin,omitempty"`
	Issuer          string                 `protobuf:"bytes,11,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Refresh         bool                   `protobuf:"varint,12,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Authenticate    string                 `protobuf:"bytes,13,opt,name=authenticate,proto3" json:"authenticate,omitempty"`
	DurationGrant   string                 `protobuf:"bytes,14,opt,name=duration_grant,json=durationGrant,proto3" json:"duration_grant,omitempty"`
	DurationToken   string                 `protobuf:"bytes,15,opt,name=duration_token,json=durationToken,proto3" json:"duration_token,omitempty"`
	DurationSession string                 `protobuf:"bytes,16,opt,name=duration_session,json=durationSession,proto3" json:"duration_session,omitempty"`
	GrantSubject    string                 `protobuf:"bytes,17,opt,name=grant_subject,json=grantSubject,proto3" json:"grant_subject,omitempty"`
	GrantToken      string                 `protobuf:"bytes,18,opt,name=grant_token,json=grantToken,proto3" json:"grant_token,omitempty"`
	GrantDuration   string                 `protobuf:"bytes,19,opt,name=grant_duration,json=grantDuration,proto3" json:"grant_duration,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccessOptions) Reset() {
	*x = AccessOptions{}
	mi := &file_protosurrealorm_anotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessOptions) ProtoMessage() {}

func (x *AccessOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protosurrealorm_anotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessOptions.ProtoReflect.Descriptor instead.
func (*AccessOptions) Descriptor() ([]byte, []int) {
	return file_protosurrealorm_anotations_proto_rawDescGZIP(), []int{0}
}

func (x *AccessOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessOptions) GetOn() string {
	if x != nil {
		return x.On
	}
	return ""
}

func (x *AccessOptions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AccessOptions) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *AccessOptions) GetIfNotExists() bool {
	if x != nil {
		return x.IfNotExists
	}
	return false
}

func (x *AccessOptions) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *AccessOptions) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AccessOptions) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AccessOptions) GetSignup() string {
	if x != nil {
		return x.Signup
	}
	return ""
}

func (x *AccessOptions) GetSignin() string {
	if x != nil {
		return x.Signin
	}
	return ""
}

func (x *AccessOptions) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AccessOptions) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

func (x *AccessOptions) GetAuthenticate() string {
	if x != nil {
		return x.Authenticate
	}
	return ""
}

func (x *AccessOptions) GetDurationGrant() string {
	if x != nil {
		return x.DurationGrant
	}
	return ""
}

func (x *AccessOptions) GetDurationToken() string {
	if x != nil {
		return x.DurationToken
	}
	return ""
}

func (x *AccessOptions) GetDurationSession() string {
	if x != nil {
		return x.DurationSession
	}
	return ""
}

func (x *AccessOptions) GetGrantSubject() string {
	if x != nil {
		return x.GrantSubject
	}
	return ""
}

func (x *AccessOptions) GetGrantToken() string {
	if x != nil {
		return x.GrantToken
	}
	return ""
}

func (x *AccessOptions) GetGrantDuration() string {
	if x != nil {
		return x.GrantDuration
	}
	return ""
}

type ModelOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	RenameAll     string                 `protobuf:"bytes,3,opt,name=rename_all,json=renameAll,proto3" json:"rename_all,omitempty"`
	In            string                 `protobuf:"bytes,4,opt,name=in,proto3" json:"in,omitempty"`
	Out           string                 `protobuf:"bytes,5,opt,name=out,proto3" json:"out,omitempty"`
	Schemafull    bool                   `protobuf:"varint,6,opt,name=schemafull,proto3" json:"schemafull,omitempty"`
	Schemaless    bool                   `protobuf:"varint,7,opt,name=schemaless,proto3" json:"schemaless,omitempty"`
	Drop          bool                   `protobuf:"varint,8,opt,name=drop,proto3" json:"drop,omitempty"`
	Permissions   string                 `protobuf:"bytes,9,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Access        *AccessOptions         `protobuf:"bytes,10,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelOptions) Reset() {
	*x = ModelOptions{}
	mi := &file_protosurrealorm_anotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelOptions) ProtoMessage() {}

func (x *ModelOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protosurrealorm_anotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelOptions.ProtoReflect.Descriptor instead.
func (*ModelOptions) Descriptor() ([]byte, []int) {
	return file_protosurrealorm_anotations_proto_rawDescGZIP(), []int{1}
}

func (x *ModelOptions) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ModelOptions) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ModelOptions) GetRenameAll() string {
	if x != nil {
		return x.RenameAll
	}
	return ""
}

func (x *ModelOptions) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *ModelOptions) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

func (x *ModelOptions) GetSchemafull() bool {
	if x != nil {
		return x.Schemafull
	}
	return false
}

func (x *ModelOptions) GetSchemaless() bool {
	if x != nil {
		return x.Schemaless
	}
	return false
}

func (x *ModelOptions) GetDrop() bool {
	if x != nil {
		return x.Drop
	}
	return false
}

func (x *ModelOptions) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

func (x *ModelOptions) GetAccess() *AccessOptions {
	if x != nil {
		return x.Access
	}
	return nil
}

type FieldOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Assert        string                 `protobuf:"bytes,4,opt,name=assert,proto3" json:"assert,omitempty"`
	Default       string                 `protobuf:"bytes,5,opt,name=default,proto3" json:"default,omitempty"`
	Permissions   string                 `protobuf:"bytes,6,opt,name=permissions,proto3" json:"permissions,omitempty"`
	LinkOne       string                 `protobuf:"bytes,7,opt,name=link_one,json=linkOne,proto3" json:"link_one,omitempty"`
	LinkMany      string                 `protobuf:"bytes,8,opt,name=link_many,json=linkMany,proto3" json:"link_many,omitempty"`
	LinkSelf      string                 `protobuf:"bytes,9,opt,name=link_self,json=linkSelf,proto3" json:"link_self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_protosurrealorm_anotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protosurrealorm_anotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_protosurrealorm_anotations_proto_rawDescGZIP(), []int{2}
}

func (x *FieldOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldOptions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldOptions) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *FieldOptions) GetAssert() string {
	if x != nil {
		return x.Assert
	}
	return ""
}

func (x *FieldOptions) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *FieldOptions) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

func (x *FieldOptions) GetLinkOne() string {
	if x != nil {
		return x.LinkOne
	}
	return ""
}

func (x *FieldOptions) GetLinkMany() string {
	if x != nil {
		return x.LinkMany
	}
	return ""
}

func (x *FieldOptions) GetLinkSelf() string {
	if x != nil {
		return x.LinkSelf
	}
	return ""
}

var file_protosurrealorm_anotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*ModelOptions)(nil),
		Field:         50001,
		Name:          "protosurrealorm.orm_model",
		Tag:           "bytes,50001,opt,name=orm_model",
		Filename:      "protosurrealorm/anotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         50002,
		Name:          "protosurrealorm.orm_field",
		Tag:           "bytes,50002,opt,name=orm_field",
		Filename:      "protosurrealorm/anotations.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional protosurrealorm.ModelOptions orm_model = 50001;
	E_OrmModel = &file_protosurrealorm_anotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional protosurrealorm.FieldOptions orm_field = 50002;
	E_OrmField = &file_protosurrealorm_anotations_proto_extTypes[1]
)

var File_protosurrealorm_anotations_proto protoreflect.FileDescriptor

const file_protosurrealorm_anotations_proto_rawDesc = "" +
	"\n" +
	" protosurrealorm/anotations.proto\x12\x0fprotosurrealorm\x1a google/protobuf/descriptor.proto\"\xab\x04\n" +
	"\rAccessOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02on\x18\x02 \x01(\tR\x02on\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\toverwrite\x18\x04 \x01(\bR\toverwrite\x12\"\n" +
	"\rif_not_exists\x18\x05 \x01(\bR\vifNotExists\x12\x10\n" +
	"\x03alg\x18\x06 \x01(\tR\x03alg\x12\x10\n" +
	"\x03key\x18\a \x01(\tR\x03key\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x16\n" +
	"\x06signup\x18\t \x01(\tR\x06signup\x12\x16\n" +
	"\x06signin\x18\n" +
	" \x01(\tR\x06signin\x12\x16\n" +
	"\x06issuer\x18\v \x01(\tR\x06issuer\x12\x18\n" +
	"\arefresh\x18\f \x01(\bR\arefresh\x12\"\n" +
	"\fauthenticate\x18\r \x01(\tR\fauthenticate\x12%\n" +
	"\x0eduration_grant\x18\x0e \x01(\tR\rdurationGrant\x12%\n" +
	"\x0eduration_token\x18\x0f \x01(\tR\rdurationToken\x12)\n" +
	"\x10duration_session\x18\x10 \x01(\tR\x0fdurationSession\x12#\n" +
	"\rgrant_subject\x18\x11 \x01(\tR\fgrantSubject\x12\x1f\n" +
	"\vgrant_token\x18\x12 \x01(\tR\n" +
	"grantToken\x12%\n" +
	"\x0egrant_duration\x18\x13 \x01(\tR\rgrantDuration\"\xa7\x02\n" +
	"\fModelOptions\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x1d\n" +
	"\n" +
	"rename_all\x18\x03 \x01(\tR\trenameAll\x12\x0e\n" +
	"\x02in\x18\x04 \x01(\tR\x02in\x12\x10\n" +
	"\x03out\x18\x05 \x01(\tR\x03out\x12\x1e\n" +
	"\n" +
	"schemafull\x18\x06 \x01(\bR\n" +
	"schemafull\x12\x1e\n" +
	"\n" +
	"schemaless\x18\a \x01(\bR\n" +
	"schemaless\x12\x12\n" +
	"\x04drop\x18\b \x01(\bR\x04drop\x12 \n" +
	"\vpermissions\x18\t \x01(\tR\vpermissions\x126\n" +
	"\x06access\x18\n" +
	" \x01(\v2\x1e.protosurrealorm.AccessOptionsR\x06access\"\xf5\x01\n" +
	"\fFieldOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06assert\x18\x04 \x01(\tR\x06assert\x12\x18\n" +
	"\adefault\x18\x05 \x01(\tR\adefault\x12 \n" +
	"\vpermissions\x18\x06 \x01(\tR\vpermissions\x12\x19\n" +
	"\blink_one\x18\a \x01(\tR\alinkOne\x12\x1b\n" +
	"\tlink_many\x18\b \x01(\tR\blinkMany\x12\x1b\n" +
	"\tlink_self\x18\t \x01(\tR\blinkSelf:]\n" +
	"\torm_model\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\v2\x1d.protosurrealorm.ModelOptionsR\bormModel:[\n" +
	"\torm_field\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\v2\x1d.protosurrealorm.FieldOptionsR\bormFieldB5Z3github.com/yaroher/surrealdb.go.orm/protosurrealormb\x06proto3"

var (
	file_protosurrealorm_anotations_proto_rawDescOnce sync.Once
	file_protosurrealorm_anotations_proto_rawDescData []byte
)

func file_protosurrealorm_anotations_proto_rawDescGZIP() []byte {
	file_protosurrealorm_anotations_proto_rawDescOnce.Do(func() {
		file_protosurrealorm_anotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protosurrealorm_anotations_proto_rawDesc), len(file_protosurrealorm_anotations_proto_rawDesc)))
	})
	return file_protosurrealorm_anotations_proto_rawDescData
}

var file_protosurrealorm_anotations_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protosurrealorm_anotations_proto_goTypes = []any{
	(*AccessOptions)(nil),               // 0: protosurrealorm.AccessOptions
	(*ModelOptions)(nil),                // 1: protosurrealorm.ModelOptions
	(*FieldOptions)(nil),                // 2: protosurrealorm.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_protosurrealorm_anotations_proto_depIdxs = []int32{
	0, // 0: protosurrealorm.ModelOptions.access:type_name -> protosurrealorm.AccessOptions
	3, // 1: protosurrealorm.orm_model:extendee -> google.protobuf.MessageOptions
	4, // 2: protosurrealorm.orm_field:extendee -> google.protobuf.FieldOptions
	1, // 3: protosurrealorm.orm_model:type_name -> protosurrealorm.ModelOptions
	2, // 4: protosurrealorm.orm_field:type_name -> protosurrealorm.FieldOptions
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protosurrealorm_anotations_proto_init() }
func file_protosurrealorm_anotations_proto_init() {
	if File_protosurrealorm_anotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protosurrealorm_anotations_proto_rawDesc), len(file_protosurrealorm_anotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_protosurrealorm_anotations_proto_goTypes,
		DependencyIndexes: file_protosurrealorm_anotations_proto_depIdxs,
		MessageInfos:      file_protosurrealorm_anotations_proto_msgTypes,
		ExtensionInfos:    file_protosurrealorm_anotations_proto_extTypes,
	}.Build()
	File_protosurrealorm_anotations_proto = out.File
	file_protosurrealorm_anotations_proto_goTypes = nil
	file_protosurrealorm_anotations_proto_depIdxs = nil
}
